import { useEffect,useState } from "react";
import { X,Star,ShoppingCart,Zap,CheckCircle2,UserCircle,MessageSquare } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { assetUrl } from "../services/api";
import { useAuth } from "../context/AuthContext";
import api from "../services/api";
import { useCart } from "../context/CartContext";

export default function ProductModal({product,onClose}){
 const nav=useNavigate(),{user}=useAuth(),{add}=useCart();
 const [data,setData]=useState({reviews:[],average:0,count:0}),[eligibility,setEligibility]=useState(null),[rating,setRating]=useState(0),[comment,setComment]=useState(""),[submitting,setSubmitting]=useState(false),[error,setError]=useState("");
 useEffect(()=>{if(!product)return;document.body.classList.add("modal-open");const esc=e=>e.key==="Escape"&&onClose();document.addEventListener("keydown",esc);api.get("/reviews/"+product._id).then(r=>setData(r.data)).catch(()=>{});if(user)api.get("/reviews/"+product._id+"/eligibility").then(r=>setEligibility(r.data)).catch(()=>setEligibility(null));return()=>{document.body.classList.remove("modal-open");document.removeEventListener("keydown",esc)}},[product,user,onClose]);
 if(!product)return null;
 const buyNow=()=>{add(product);nav("/checkout");};
 const submit=async e=>{e.preventDefault();if(!rating)return setError("Select a rating first");setSubmitting(true);setError("");try{await api.post("/reviews/"+product._id,{rating,comment});const r=await api.get("/reviews/"+product._id);setData(r.data);setEligibility({purchased:true,canReview:false,alreadyReviewed:true});setRating(0);setComment("");}catch(x){setError(x.response?.data?.message||"Could not submit review");}finally{setSubmitting(false)}};
 return <div className="product-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="product-modal"><button className="modal-close" onClick={onClose} aria-label="Close"><X size={19}/></button>
 <div className="modal-product-grid"><div className="modal-image-wrap"><img src={product.image_name?assetUrl(product.image_name):"https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1000"} alt={product.name}/><span className="modal-stock">{product.stock>0?"IN STOCK":"OUT OF STOCK"}</span></div>
 <div className="modal-info"><p className="eyebrow">TECH NEXUS PICK</p><h2>{product.name}</h2><div className="rating-line"><Stars average={data.average}/><b>{Number(data.average||0).toFixed(1)}</b><span>{data.count} review{data.count===1?"":"s"}</span></div><p className="modal-desc">{product.description||"Premium technology for the modern world."}</p><div className="modal-price-row"><strong>Rs {Number(product.price).toLocaleString("en-IN")}</strong><span>{product.stock} available</span></div><div className="modal-actions"><button className="primary" disabled={!product.stock} onClick={buyNow}><Zap size={17}/>Buy now</button><button className="modal-cart" disabled={!product.stock} onClick={()=>add(product)}><ShoppingCart size={17}/>Add to cart</button></div><div className="modal-note"><CheckCircle2 size={15}/>Cash on Delivery available • secure checkout</div></div></div>
 <div className="modal-lower"><section className="modal-section"><div className="modal-section-title"><h3>Product features</h3><span>{product.features?.length||0} highlights</span></div>{product.features?.length?<div className="feature-list">{product.features.map((f,i)=><div key={i}><CheckCircle2 size={15}/>{f}</div>)}</div>:<p className="modal-muted">Features will appear here when the product is updated with highlights.</p>}</section>
 <section className="modal-section reviews-section"><div className="modal-section-title"><h3>Customer reviews</h3><span><MessageSquare size={14}/> {data.count}</span></div>{data.reviews?.length?<div className="reviews-list">{data.reviews.map(r=><article className="review" key={r._id}><div className="review-head"><div className="review-user"><span className="review-avatar">{r.user?.name?.charAt(0)?.toUpperCase()||"U"}</span><div><b>{r.user?.name||"Customer"}</b><small>{new Date(r.createdAt).toLocaleDateString("en-IN")}</small></div></div><Stars average={r.rating} small/></div><p>{r.comment}</p><span className="verified-review"><CheckCircle2 size={12}/>Verified purchase</span></article>)}</div>:<p className="modal-muted">No reviews yet. Be the first customer to share your experience.</p>}</section>
 <section className="modal-section review-form-section"><div className="modal-section-title"><h3>Share your experience</h3></div>{!user?<div className="review-gate"><UserCircle size={22}/><div><b>Sign in to leave a review.</b><small>You can review products you have purchased.</small></div></div>:eligibility?.canReview?<form className="review-form" onSubmit={submit}><div className="rating-picker"><span>Your rating</span><div>{[1,2,3,4,5].map(n=><button type="button" key={n} className={n<=rating?"picked":""} onClick={()=>setRating(n)}><Star size={21}/></button>)}</div></div><textarea required minLength={3} maxLength={600} placeholder="What did you like about this product?" value={comment} onChange={e=>setComment(e.target.value)}/>{error&&<div className="error">{error}</div>}<button className="primary" disabled={submitting}>{submitting?"Posting...":"Post review"}</button></form>:<div className="review-gate"><CheckCircle2 size={22}/><div><b>{eligibility?.alreadyReviewed?"Thanks for your review!":"Purchase this product to review it."}</b><small>{eligibility?.alreadyReviewed?"You can only submit one review per product.":"Reviews are available to customers who have purchased this product."}</small></div></div>}</section></div>
 </div></div>;
}
function Stars({average,small=false}){const n=Number(average||0);return <div className={"stars "+(small?"small":"")}>{[1,2,3,4,5].map(i=><Star key={i} size={small?13:15} fill={i<=Math.round(n)?"currentColor":"none"}/>)}</div>}